require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Mihuro' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
    
#  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
#
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
#
#  pod 'RNSVG', :path => '../node_modules/react-native-svg'
#
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
#
#  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
#
#  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
#
#  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
#
#  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'MihuroTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
  end
end
